[package]
name = "vl6180x-ner"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal-async.workspace = true
embedded-hal.workspace = true
int-enum = {version = "0.4.0", default-features = false}